### ISSUE TITLE
awesome logo

### ISSUE THREAD

**Issue by boneskull** [digsjs/digs#12]
either I learn how to make vector art or someone who does helps me.  

#8 should use the same color scheme.  maybe a purple/blue or purple/yellow scheme?  see [wiki: Color Psychology](http://wikipedia.org/wiki/Color_psychology#Specific_color_meaning)

**Comment by danielstjules** [comment]
Any other thoughts on the logo, aside from color? :)

**Comment by boneskull** [comment]
I'm thinking a very simple house shape:

![house icon](http://www.iconsdownload.net/icons/256/1465-simple-house-thin-outline-icon.png)

with a OSH logo in it:

![osh logo](http://www.iotbe.org/website/image/ir.attachment/658_b48d621/datas)
